### ISSUE TITLE
Task research

### ISSUE THREAD

**Issue by allanhortle** [bigdatr/stampy#1]
Also see https://github.com/bigdatr/bd-stampy/issues/24
- Spruce class naming will be used on all components
- Separation of structural styles and visual styles
- Perhaps some default visual styles?
- Should we also include basic layout components like `Wrapper` or `Grid` which are just divs with a chosen class name and spruce class naming abilities?
- ES6 with babel
- JSDOC
- Tests with tape
- Some kind of docs with live demo and editing of props
- Categorise components more clearly (e.g. hocks get their own folder)
### bd-stampy
- components/AutoRequest.jsx
  - Rename to PropChangeListenerHock
- components/DataTable.jsx
  - onPaginate should just provide `(page)` to callback and not `(event, page)`
- components/FindChild.jsx 
  - Used by Tabs
- components/Pagination.jsx
- components/QueryStringProvider.jsx
- components/Table.jsx
- utils/ComponentClassNames.js `uses classnames`
- utils/Paginate.js
- components/Button.jsx
- components/Media.jsx
- components/Label.jsx
### move from toyota-styles
- AutosuggestInput.jsx `// uses react-autosuggest`
- Modal.jsx `// uses react-modal, add prop to allow it to manage its own component`
- ResponsiveTabs.jsx `// rename this to something else, becomes a select when small`
- Select.jsx `// uses react-select`
  - make the current `onChangeString` behaviour the default.
  - queryString needs to be fixed, could use QueryStringProvider
- TabContent.jsx
  - onTabSelect should be onChange
  - fallbackTab should be defaultTab and should default to 0
  - `queryString="paramName"` could use QueryStringProvider to automatically save tab state to the query string
- TabContentItem.jsx
- Tabs.jsx
## Re-write
- components/Checkbox.jsx `Add a checkbox group for making ToggleBoxes`
- components/Carousel.jsx `Was never finished`
- components/DatePicker.jsx `Is cray. We should either use react-dates, or react-day-picker`
- components/Dropdown.jsx
- components/Img.jsx `needs better support for lazy-loading, fallbacks. Needs less messed up size things`
- components/Code.jsx `Probably needs a name change. Some simple preformattted code viewer`
- components/ProgressBar.jsx `use chekts`
- components/ShowHide.jsx `Good idea, too many mixins though`
- components/Input.jsx
- components/Textarea.jsx
- components/InputRow.jsx `needs more options for pre and post areas`
## Ditch
- All mixins
- components/Select.jsx `// toyota-styles/Select.jsx using react select covers this`
- components/SelectStandard.jsx `// toyota-styles/Select.jsx using react select covers this`
- components/SelectStandardForm.jsx `// unnecessary mixin`
- components/Tab.jsx `toyota-styles/Tab components do this a little better`
- components/TabContent.jsx `toyota-styles/Tab components do this a little better`
- components/TabView.jsx `toyota-styles/Tab components do this a little better`
- components/Tabs.js `Unnecessary import grouping`
- utils/ClassBuilder.js `use either classnames or componentClassNames`
- utils/BrowserHistory.js `BYO router, most projects will have react-router, + Atridge voted to ditch in #24`
- utils/Url.js `BYO router, most projects will have react-router, + Atridge voted to ditch in #24`
- utils/UrlStore.js `BYO router, most projects will have react-router, + Atridge voted to ditch in #24`
- components/Animation.jsx
- components/Config.jsx
- components/Fieldset.jsx
- components/Iframe.jsx
- components/Td.jsx `Unnecessary as component, unless we want spruce abilites?`
- components/Tr.jsx `Unnecessary as component, unless we want spruce abilites?`
- utils/History.js
- components/_Checkbox.jsx
- components/RadioButton.jsx
## Move to BigDatr
- components/FileUpload.jsx
- components/ImageUpload.jsx
- utils/CSS.js `Might need to be moved to Peanut`
- utils/Maths.js
- utils/Key.js

**Comment by dxinteractive** [comment]
Outdated now!
