### ISSUE TITLE
Add placeholder prop to input component

### ISSUE THREAD

**Issue by dxinteractive** [bigdatr/stampy#122]
To be applied as a `placeholder` attribute on the `<input />`.

Currently apps have been getting around this missing prop by using `htmlProps`, which is an object whose keys/values are spread onto the `<input />`.

Also if you could update the jsdoc comments, proptypes and flowtypes related to the new prop, they're all in that input file along with the other props. Its kind of duplicative but havent found a better way yet.

**Comment by mriccid** [comment]
Closing as the fix for this has been merged
