### ISSUE TITLE
component/ResponsiveTabs

### ISSUE THREAD

**Issue by allanhortle** [bigdatr/stampy#20]
rename this to something else, becomes a select when small

**Comment by dxinteractive** [comment]
If we are to use `ToggleGroup` for the clickable set of tabs, and a `ConditionalChildren` component to show children, then responsive tabs could be a similar thing to a normal `Tabs` except it replaces the `ToggleGroup` with a `Select` under certain circumstances.

**Comment by dxinteractive** [comment]
Lets forget about this until we really need it.
