### ISSUE TITLE
component/TabSet

### ISSUE THREAD

**Issue by allanhortle** [bigdatr/stampy#23]

**Comment by dxinteractive** [comment]
`TabSet` can use the same props interface as all inputs. It can expect to be passed children `Tab` components with unique `name` props, and where each `Tab`'s child elements make up the contents of each tab panel. Internally `TabSet` can implement a `ToggleGroup` for the clickable tab buttons, possibly with a "tabs" modifier by default, and also use a `ConditionalChildren` to choose which tab's content will be displayed.

**Comment by dxinteractive** [comment]
Now with React Router 4 this is really easy. `Tab` and `TabSet` are just spruce components that dont need to be in stampy. If using RR4 then go:

```
<TabSet>
    <Link to="/tab1" className="Tab" activeClassName="Tab-active">Tab 1</Link>
    <Link to="/tab1" className="Tab" activeClassName="Tab-active">Tab 1</Link>
</TabSet>
```

Where `<TabSet />` is `<div className="TabSet" />`.

If you'd rather use state, probably use a `ToggleSet` with spruce names of "TabSet" and "Tab", and show the correct state yourself. Unsure if we have enough use case for that to put anything in stampy, as the router option is nearly always better.
