### ISSUE TITLE
hock/ConditionalChildren

### ISSUE THREAD

**Issue by allanhortle** [bigdatr/stampy#25]

**Comment by allanhortle** [comment]
@dxinteractive has called this one as useless. Will just be implemented directly in the Tabs
#23

**Comment by dxinteractive** [comment]
On second thought, lets reopen this as a conditional children thing, that by default can possibly accept a `value` string that shows a child with a corresponding `name` (fitting with forms), or accept a function to allow for more flexible filtering of children. `Tabs` can use it.

**Comment by dxinteractive** [comment]
Yeah, its useless. React router 4 is great.
