### ISSUE TITLE
component/AutosuggestInput

### ISSUE THREAD

**Issue by allanhortle** [bigdatr/stampy#4]
uses react-autosuggest

**Comment by allanhortle** [comment]
@dxinteractive should this be a hock that can be applied to input?

**Comment by dxinteractive** [comment]
@allanhortle hmm, that might be more hassle than its worth. What would we gain from having it as a hock, like what else would it be used with?

**Comment by dxinteractive** [comment]
Actually, would be cool to have it as a hock for the sake of inheriting features and behaviour from `Input` yeah, not sure what mad amounts of hooking up it would need with an autosuggest plugin though, they normally assume you aren't providing your own inputs.
