### ISSUE TITLE
Should we move tests somewhere?

### ISSUE THREAD

**Issue by dancoates** [bigdatr/stampy#56]
I think it could get a bit annoying trying to find the file that you want in amongst a bunch of similarly named files in the same folder. Especially in a folder like hocks that has a few things in it. I'm not sure if it will happen again but I also had to create two test files for ElementQueryHock, one with a browser like setup including window and document globals and one with a server like setup. If we have to do that a few times then it could get a bit out of hand.
 
![screen shot 2016-11-28 at 12 33 45 pm](https://cloud.githubusercontent.com/assets/1946998/20653807/fdad3ef8-b566-11e6-9d1c-1a986f7ce95e.png)

I'm also not really a fan of `__test__` folders but could we just put them in a folder called `test` next to the file they are testing?

**Comment by dxinteractive** [comment]
I'm happy to use either `test` or `__test__` inside of each Components directory.

**Comment by dxinteractive** [comment]
Lets go `__test__`!

**Comment by dancoates** [comment]
👍
