### ISSUE TITLE
Eslint is broke

### ISSUE THREAD

**Issue by dancoates** [bigdatr/stampy#66]
Doesn't actually really lint anything...

**Comment by dxinteractive** [comment]
Oh

**Comment by dancoates** [comment]
To add more detail – we need to update to the newest version of `eslint-config-blueflag` and update the package json scripts to:

```
    "lint": "eslint src --ext js,jsx",
    "lint-fix": "eslint src --ext js,jsx --fix",
```

**Comment by allanhortle** [comment]
Fixed now.
