### ISSUE TITLE
Refactor hocks to have consistent signature

### ISSUE THREAD

**Issue by dancoates** [bigdatr/stampy#77]
Accept a function as first parameter with props and possibly state. If the return value of the function is false then the hock should just act as a transparent wrapper and not do anything.

**Comment by dxinteractive** [comment]
So the function can re-config the hock when props change?

If so, how will we cope with config that cannot be changed after initial config? Most config is used within the component which mean we can re-config it based on props, but if a hock were to export different hock components based on config then this cannot be changed after an initial execution of the config function. And in that case the initial execution would have to occur before componentWillMount, and therefore not have any props to provide the first time around.

I'd kind of prefer it if config is an object, and value on that config object can be functions which provide props if it makes sense for that config options to re-evaluate based on props.
